project:
  type: website

website:
  favicon: apple-touch-icon.png
  navbar:
    background: "#000066"
    foreground: "#FBF8F4"
    right:
      - about.qmd
      - href: https://linksta.cc/@jdst258
        text: Social Media ![](/linkstacc.png){height=1.5em}
    left: 
    - href: index.qmd 
      text: Home
      
format:
  html:
    theme:
      light: litera
      dark: darkly
    css: styles.css
editor: visual

